steps:
  # Step 1: A simple "Hello World" to test the connection
  #- name: 'github/super-linter:latest'
   # env:
    #  - 'VALIDATE_ALL_CODEBASE=false' # Only lint changed files to save time
     # - 'GITHUB_TOKEN=$_GITHUB_TOKEN'
      #- 'GITHUB_SHA=$COMMIT_SHA'
      #- 'GITHUB_EVENT_NAME=push'
     # - 'GITHUB_WORKSPACE=/workspace'
     # - 'GITHUB_EVENT_PATH=/dev/null' 
     # - 'RUN_LOCAL=true'
     # - 'ACTIONS_RUNNER_DEBUG=true'
    
  # Step 2: Run a basic syntax check (Linter)
  - name: 'python:3.10-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y git
        pip install google-genai
        python ai_reviewer_script.py
    env:
      - 'API_KEY=$_GEMINI_API_KEY'

options:
  logging: CLOUD_LOGGING_ONLY
